config/routes.rb
Uploader::Application.routes.draw do
  resources :studentusers

  resources :students

  resources :belllapadula

  match 'diffiehellman/calculator' => 'diffiehellman#calculator'
  resources :diffiehellman

  resources :linux
  match '/users' => 'upload#index'
  match '/supersecretusercontroller' => 'users#index'
  resources :users
  match 'student/help' => 'student#help'
  
  match '/studentuser/notfound' => 'studentuser#notfound'
  root :to => 'upload#index'

  resources :upload
  resources :student
  
  resources :winsec

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/studentuser.rb
class Studentuser < ActiveRecord::Base
end

app/controllers/studentusers_controller.rb
class StudentusersController < ApplicationController
  # GET /studentusers
  # GET /studentusers.xml
  def index
    @studentusers = Studentuser.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @studentusers }
    end
  end
  
  # GET /studentusers/1
  # GET /studentusers/1.xml
  def show
    @studentuser = Studentuser.find_by_stil(params[:stil])
    if @studentuser.nil?
      return
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @studentuser }
    end
  end
  
  def notfound
    
  end

  # GET /studentusers/new
  # GET /studentusers/new.xml
  def new
    @studentuser = Studentuser.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @studentuser }
    end
  end

  # GET /studentusers/1/edit
  def edit
    @studentuser = Studentuser.find(params[:id])
  end

  # POST /studentusers
  # POST /studentusers.xml
  def create
    @studentuser = Studentuser.new(params[:studentuser])

    respond_to do |format|
      if @studentuser.save
        format.html { redirect_to(@studentuser, :notice => 'Studentuser was successfully created.') }
        format.xml  { render :xml => @studentuser, :status => :created, :location => @studentuser }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @studentuser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /studentusers/1
  # PUT /studentusers/1.xml
  def update
    @studentuser = Studentuser.find(params[:id])

    respond_to do |format|
      if @studentuser.update_attributes(params[:studentuser])
        format.html { redirect_to(@studentuser, :notice => 'Studentuser was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @studentuser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /studentusers/1
  # DELETE /studentusers/1.xml
  def destroy
    @studentuser = Studentuser.find(params[:id])
    @studentuser.destroy

    respond_to do |format|
      format.html { redirect_to(studentusers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/studentusers_helper.rb
module StudentusersHelper
end

app/views/studentusers/_form.html.erb
<%= form_for(@studentuser) do |f| %>
  <% if @studentuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@studentuser.errors.count, "error") %> prohibited this studentuser from being saved:</h2>

      <ul>
      <% @studentuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stil %><br />
    <%= f.text_field :stil %>
  </div>
  <div class="field">
    <%= f.label :project0 %><br />
    <%= f.check_box :project0 %>
  </div>
  <div class="field">
    <%= f.label :project1 %><br />
    <%= f.check_box :project1 %>
  </div>
  <div class="field">
    <%= f.label :project2 %><br />
    <%= f.check_box :project2 %>
  </div>
  <div class="field">
    <%= f.label :project3 %><br />
    <%= f.check_box :project3 %>
  </div>
  <div class="field">
    <%= f.label :project4 %><br />
    <%= f.check_box :project4 %>
  </div>
  <div class="field">
    <%= f.label :project5 %><br />
    <%= f.check_box :project5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studentusers/edit.html.erb
<h1>Editing studentuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @studentuser %> |
<%= link_to 'Back', studentusers_path %>

app/views/studentusers/index.html.erb
<h1>Listing studentusers</h1>

<table border=1>
  <tr>
    <th>Stil</th>
    <th>Certificates</th>
    <th>Tracker</th>
    <th>Linux AC</th>
    <th>DH MITM</th>
    <th>Windows AC</th>
    <th>Bell-LaPadula</th>
    <th>Total</th>
    <th></th>
  </tr>

<% @studentusers.each do |studentuser| %>
  <tr>
    <td><%= studentuser.stil %></td>
    <td><%= studentuser.project0 %></td>
    <td><%= studentuser.project1 %></td>
    <td><%= studentuser.project2 %></td>
    <td><%= studentuser.project3 %></td>
    <td><%= studentuser.project4 %></td>
    <td><%= studentuser.project5 %></td>
    <td><%= studentuser.project0 && studentuser.project1 && studentuser.project2 && studentuser.project3 && studentuser.project4 && studentuser.project5  %></td>
    <td><%= link_to 'Destroy', studentuser, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Studentuser', new_studentuser_path %>

app/views/studentusers/new.html.erb
<h1>New studentuser</h1>

<%= render 'form' %>

<%= link_to 'Back', studentusers_path %>

app/views/studentusers/notfound.html.erb
No projects completed yet for this user

app/views/studentusers/show.html.erb
<p id="notice"><%= notice %></p>

<% if @studentuser.nil? then %>
	En student med detta STIL-ID kunde inte hittas
<% else %>
	<p>
	  <b>Stil:</b>
	  <%= @studentuser.stil %>
	</p>
	
	<p>
	  <b>Certificate Chains:</b>
	  <%= @studentuser.project0 %>
	</p>
	
	<p>
	  <b>Tracker Attack:</b>
	  <%= @studentuser.project1 %>
	</p>
	
	<p>
	  <b>Linux Access Control:</b>
	  <%= @studentuser.project2 %>
	</p>
	
	<p>
	  <b>Diffie-Hellman MITM:</b>
	  <%= @studentuser.project3 %>
	</p>
	
	<p>
	  <b>Windows Access Control:</b>
	  <%= @studentuser.project4 %>
	</p>
	
	<p>
	  <b>Bell-LaPadula:</b>
	  <%= @studentuser.project5 %>
	</p>
<% end %>